spring.application.name=money-flow

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/money_flow


telegram.url=https://api.telegram.org/bot
telegram.timeout=15

spring.profiles.active=local
